### ISSUE TITLE
Feature request: Disabling "Repeat Drill" hotkey

### ISSUE THREAD

**Issue by ghost** [JoshuaGrams/steno-jig#38]
Hello Joshua Grams,

Great widget! I've been using and enjoying it a lot!
One request: it happens once and again that I hit `R*R` by mistake, and I find it very frustrating to have to start all over again. If it is not too difficult, do you think it would be possible to add a toggle (like for showing hints) for enabling/disabling the "repeat drill" hotkey?
Alternatively, do you think you could direct me at where I can make the change to disable/ replace the "enter" as the hotkey? I don't know my way around JavaScript and when I downloaded a local copy I tried to remove the `<a id="again" title="Enter">&#8634; Repeat Drill <span class="shortcutkey">(Enter)</span></a>` from the "navigation center" but that, instead, just broke the whole thing down. Oops. 

Thanks in advance!

**Comment by na2hiro** [comment]
Hi, it's me who added the shortcut feature and chose enter key for that command (#34). Sorry for the trouble! I chose the key just because it was not used for anything and also pressing it caused strange behavior on UI (if I remember correctly).

In my humble opinion, it would be simpler just to reassign to another key which is more difficult to press mistakenly. For example: Arrow Up, Escape

**Comment by JoshuaGrams** [comment]
Yeah, I was never convinced about that feature. It seemed like it was asking for trouble, and it's not that much faster than just hitting Tab a couple of times to get to the link you want.  But we haven't had any complaints until now.

If you want to disable just the Restart hotkey, the code is here: https://github.com/JoshuaGrams/steno-jig/blob/gh-pages/type-jig.js#L152

Or you could disable the whole hotkey thing entirely by deleting or commenting out this line: https://github.com/JoshuaGrams/steno-jig/blob/gh-pages/type-jig.js#L25

**Comment by ghost** [comment]
Great, thanks! That works.
Hitting return does cause a strange but reversible behaviour; the blinker (marker of typing, whatever that's called) goes one line down. If you continue typing then things would go awry, but if you just hit backspace you are back to order.

Thanks again! 
And this is not something I currently need, but I guess indeed one could have the shortcut being something less commonly used*, and one could perhaps disable the return key altogether?


* of course with qwerty it's hard to hit return by mistake, but with steno it's easy to dance on your partner's feet and land on the fatal combination. "Return" is a common typographical "sigh" and therefore an easy stroke to make.
