### ISSUE TITLE
Hello Joshua - How is WPM calculated? Something doesn't fully add up. 

### ISSUE THREAD

**Issue by carcinosgb** [JoshuaGrams/steno-jig#40]
Dear Joshua, I just did a test with a metronome at 85BPM. And as you can see I typed 170 incorrect words on a 2 min exercise. Even in that case it says the WPM is 68WPM? Shouldn't it be 85 WPM?  I did another test with 60 correct words on a 2min exercise and instead of 30WPM it came out to 25WPM. I then did another test with longer words, wrote 60 and came out to 38WPM this time. It's as if the WPM were calculated based on a parameter other than actual words! I don't know how to read code that's why I ask :S Thank you

[screencapture-joshuagrams-github-io-steno-jig-learn-plover-html-2020-03-30-12_51_32.pdf](https://github.com/JoshuaGrams/steno-jig/files/4402223/screencapture-joshuagrams-github-io-steno-jig-learn-plover-html-2020-03-30-12_51_32.pdf)

**Comment by carcinosgb** [comment]
Ok I actually looked at the files and was surprised to be able to understand that every 5 characters is counted as a word! Understood! Thank you.

**Comment by JoshuaGrams** [comment]
Yes, just counting characters (including spaces and punctuation) and dividing by 5 is the standard for typing competitions and such. It avoids the inconsistency of some words being longer than others. And for most English texts it comes out within 10% or so of the actual value, so it's a decent compromise.

**Comment by carcinosgb** [comment]
Thank you so much for the detailed explanation Joshua.
