### ISSUE TITLE
copy paste problem

### ISSUE THREAD

**Issue by benjamind8191** [JoshuaGrams/steno-jig#44]
Hello, your site is really great. I have been inserting my own word lists into the custom boxes to practice. The problem I'm having is that when I write the words with the steno keyboard w/ plover into notepad and then copy and paste it into your word box, nothing shows up when it loads the exercise. I have to type the words with my normal qwerty keyboard no plover and  the exercise shows up properly but it would be preferable/faster and better for my practice to be able to just write the words in steno. Is there anything I can do about this?

Thank you so much for this website, it is a really great tool, and I am enjoying using it.

**Comment by aerickt** [comment]
Make sure there is no space preceding your text. Since you're writing with Plover, there will probably be a space before your first word, which you can eliminate by first chording `TK-LS` or `KPA*` if you want the first word to be capitalised.

**Comment by JoshuaGrams** [comment]
Oops, that's bad. Pushed a quick fix. Thanks, @aerickt!

**Comment by benjamind8191** [comment]
I should have tried it again today before I created the issue. I did and it
worked right away. The last time I think I was just writing the text
directly into the box and the space must have been causing the problem.
Damn space. Thank you.

**Comment by aerickt** [comment]
> Oops, that's bad. Pushed a quick fix. Thanks, @aerickt!

You're welcome! Sorry for not creating an issue earlier, I'm still new to this whole GitHub thing.
