### ISSUE TITLE
More alternative (British) spellings to match

### ISSUE THREAD

**Issue by hftf** [JoshuaGrams/steno-jig#54]
Appreciate the feature so far! Today I encountered `behaviours` and `flavours`, which aren't in the 140 or so being matched. Maybe there's a way to import a more complete dictionary of US–British equivalents?

**Comment by JoshuaGrams** [comment]
Yeah, I only went through the New General Service List that the top X words and gutenberg sentences are working from, and wrote up the ones I found. It didn't seem like there was an easy way to do it algorithmically (I initially thought it would just be matching -or against -our and -ize against -ise but it wasn't that simple), and a quick search didn't turn up a dictionary of US/British equivalents.

I'd certainly be open to importing a dictionary if you know of some open-licensed data that wouldn't be an outrageous amount of work to reformat...

**Comment by hftf** [comment]
I suppose this could work? http://www.openstenoproject.org/stenodict/dictionaries/uk.html It was linked somewhere...

**Comment by JoshuaGrams** [comment]
Ohhh...that totally never occurred to me. And they can be matched up to the US versions through the steno outlines. Very smart.

We have a farm so this is the busy season and have family visiting for a couple weeks, so I'm not sure how soon I'll get to it, but yeah, that should work. Thanks!
