### ISSUE TITLE
[Suggestion] Emily's Symbol Dictionary, Jeff's Phrasing and Python dictionary training

### ISSUE THREAD

**Issue by Monniasza** [JoshuaGrams/steno-jig#60]
Hi, I want to study Emily's Symbol Dictionary interactively, but Typey Type refuses to load its JSON form. Additionally, I've had issues with spacing in the Typey Type's lesson. Maybe I could generate the material with Python, but I'd feel like having per-lesson-generated material. I'm now to working on this project, and I don't know where to start making my own code for the dictionary. I hope you will guide me on working on Steno Jig's code to generate Emily's Symbol Dictionary strokes for lessons.

**Comment by Monniasza** [comment]
The Steno Jig does not handle unspaced words well.

**Comment by Monniasza** [comment]
![image](https://github.com/JoshuaGrams/steno-jig/assets/37037712/2780af18-97ee-4a9b-b586-943ceb70a4e0)
The initial state of the exercise

![image](https://github.com/JoshuaGrams/steno-jig/assets/37037712/c92b963c-c653-4a2f-827b-2c08ff29dc28)


![image](https://github.com/JoshuaGrams/steno-jig/assets/37037712/2661c1b3-e33e-4a8f-bf6b-94d7325d2252)
Steno Jig does not handle exercises without spaces correctly

**Comment by Monniasza** [comment]
Additionally, plurals are cut out from later strokes despited being required in them

**Comment by Monniasza** [comment]
I'm working on it at #61.

**Comment by Monniasza** [comment]
My prototype kinda works. The plurals are shown unreliably, so I'll scrap repetition and require both spaces in every stroke. The aim of this trainer is to primarily teach symbols. Some symbols are hard to distinguish (like 2 apostrophes and a quote, or 3 periods and an ellipsis).

**Comment by Monniasza** [comment]
@JoshuaGrams My prototype is finished! Check out the pull request!

**Comment by JoshuaGrams** [comment]
Yeah, sorry to be slow, I have a busy several days here...
